[package]
name = "itolib"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = "0.4.38"
day_count_conventions = "0.1.4"
num = "0.4.3"
rust_decimal = { version = "1.35.0", optional = true }
rust_decimal_macros = { version = "1.35.0", optional = true }

[features]
high_precision = ["dep:rust_decimal", "dep:rust_decimal_macros"]

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "katex_header.html", "--cfg", "docsrs"]
