[package]
name = "itolib-instruments"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license-file.workspace = true
readme.workspace = true

[dependencies]
itolib-money.workspace = true
itolib-time.workspace = true
